id: PD99D60D6
initial_creation_type: input
source_metadata:
  title: Seven Branches Series
  language: bo
  description: Texts on the theme of the seven-branch (yan lag bdun pa; saptāṅga)
    service, commonly consisting of 1) prostration/homage, 2) making offerings, 3)
    confession of negative actions, 4) rejoicing in others' virtue, 5) requesting
    the turning of the dharma wheel, 6) imploring teachers to remain and not pass
    into parinirvāṇa, and 7) dedicating merit to the enlightenment of all sentient
    beings.
  volume:
    cb3c016282a2410fbd27c70aa91faf0f:
      title: Seven-Branch Offering to Tārā
      parent: Practices
    4ce5d2d4a90a477882cf9ee7cfd98d1c:
      title: The Seven Branches for Practising the Sacred Dharma
      parent: Practices
    37fc7cc06fb449658fee550e119b51c6:
      title: The Eight-Branch Offering from the Gyüluk Phurba
      parent: Eight Branches
created_at: '2022-03-01T05:44:10.779409'
last_modified_at: '2022-03-01T05:44:10.779411'
